- ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\System
    name: MSAOptional
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\Explorer
    name: NoAutoplayfornonVolume
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoAutorun
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Explorer
    name: NoDriveTypeAutoRun
    data: 255
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\SOFTWARE\Policies\Microsoft\Biometrics\FacialFeatures
    name: EnhancedAntiSpoofing
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\FVE
    name: DisableExternalDMAUnderLock
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\FVE
    name: UseEnhancedPin
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Application
    name: MaxSize
    data: 32768
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\Security
    name: MaxSize
    data: 196608
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\EventLog\System
    name: MaxSize
    data: 32768
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: EnableSmartScreen
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\System
    name: ShellSmartScreenLevel
    data: Block

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Internet Explorer\PhishingFilter
    name: EnabledV9
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\AxInstaller
    name: OnlyUseAXISForActiveXInstall
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Internet Explorer\Security
    name: DisableSecuritySettingsCheck
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: PreventIgnoreCertErrors
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Internet Explorer\Download
    name: RunInvalidSignatures
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: CertificateRevocation
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Internet Explorer\Download
    name: CheckExeSignatures
    data: 'yes'

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: SecureProtocols
    data: 2560
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: WarnOnBadCertRecving
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1406'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1407'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1802'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2402'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: 120b
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: 120c
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1206'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2102'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1209'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2103'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: 140C
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2200'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: 270C
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1004'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2709'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2708'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: 160A
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1201'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: 1C00
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1804'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: 1A00
    data: 65536
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1607'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2004'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2001'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1806'
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1409'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2500'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2301'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1809'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '1606'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\3
    name: '2101'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1
    name: 270C
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1
    name: '1201'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\1
    name: '1C00'
    data: 65536
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0
    name: 270C
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\0
    name: 1C00
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\3
    name: '2301'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\1
    name: 1C00
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\0
    name: 1C00
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\4
    name: 1C00
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\4
    name: '2301'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Lockdown_Zones\2
    name: 1C00
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1406'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1400'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2000'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1407'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1802'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1803'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2402'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1608'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: 120b
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: 120c
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1206'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1209'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: 140C
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2200'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: 270C
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1001'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1004'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2709'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2708'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: 160A
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1201'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: 1C00
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1804'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: 1A00
    data: 196608
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1607'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2004'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2001'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1200'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1405'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1402'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1806'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1409'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2500'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2301'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1809'
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '1606'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\4
    name: '2101'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2
    name: 270C
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2
    name: '1201'
    data: 3
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings\Zones\2
    name: 1C00
    data: 65536
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windows\CurrentVersion\Internet Settings
    name: EnableSSL3Fallback
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Ext
    name: RunThisTimeEnabled
    data: 0
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Microsoft\Windows\CurrentVersion\Policies\Ext
    name: VersionCheckEnabled
    data: 1
    type: dword
