- community.windows.win_security_policy:
    section: System Access
    key: PasswordHistorySize
    value: 24
  
- community.windows.win_security_policy:
    section: System Access
    key: MinimumPasswordLength
    value: 14

- community.windows.win_security_policy:
    section: System Access
    key: PasswordComplexity
    value: 1

- community.windows.win_security_policy:
    section: System Access
    key: ClearTextPassword
    value: 0
