
- community.windows.win_firewall:
    state: enabled
    inbound_action: Block
    outbound_action: Allow
    profiles: domain,private,public

- ansible.builtin.include_tasks: registry.yml
  loop:
    - Domain
    - Private
    - Public
  loop_control:
    loop_var: profile
