- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\WindowsFirewall\{{ profile }}Profile
    name: DisableNotifications
    data: 1
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\{{ profile }}profile\Logging
    name: LogFileSize
    data: 16384
    type: dword

- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\{{ profile }}profile\Logging
    name: LogDroppedPackets
    data: 1
    type: dword
    
- ansible.windows.win_regedit:
    path: HKLM:\Software\Policies\Microsoft\Windowsfirewall\{{ profile }}profile\Logging
    name: LogSuccessfulConnections
    data: 1
    type: dword

